services:
  - type: web
    name: relier-builder
    runtime: node
    rootDir: builder
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
